version: "3.8"

services:

  accounts:
    image: darshm/bankapplication:accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - darshm-network

  loans:
    image: darshm/bankapplication:loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - darshm-network

  cards:
    image: darshm/bankapplication:cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - darshm-network

networks:
  darshm-network: