version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - darshm-network

  configserver:
    image: darshm/bankapplication:configserver
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - darshm-network
    depends_on:
      - zipkin
   
  eurekaserver:
    image: darshm/bankapplication:eurekaserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - darshm-network
    depends_on:
      - configserver
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
  accounts:
    image: darshm/bankapplication:accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - darshm-network
    depends_on:
      - configserver
      - eurekaserver
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  
  loans:
    image: darshm/bankapplication:loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - darshm-network
    depends_on:
      - zipkin
      - configserver
      - eurekaserver
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
  cards:
    image: darshm/bankapplication:cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - darshm-network
    depends_on:
      - zipkin
      - configserver
      - eurekaserver
      - accounts
      - loans
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
   
  gatewayserver:
    image: darshm/bankapplication:gatewayserver
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - darshm-network
    depends_on:
      - zipkin
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
networks:
  darshm-network: